12 add support for paraspell sdk
kodadot/sub-scaffold pull request #43
Opened 2022-12-21 14:32 UTC by brano-hozza

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Fix
- [x] Feature
- [x] Refactoring
- [ ] Chore

### What's new?

- [x] PR closes #12 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR
- [ ] I've written some unit tests 🧪

### Optional

- [ ] I found edge cases

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

2022-12-21 19:59 UTC, dudo50 approved these changes

2022-12-22 20:26 UTC, vikiival requested changes
Please unify casing across the app in template files. 

Move paradspell to separated route see latest issue

2022-12-22 20:26 UTC, vikiival commented on components/assets/AssetComponent.vue
> +  width: 200px;
Why fixed width?

2022-12-22 20:26 UTC, vikiival commented on stores/AssetsStore.ts
> +import { NODE_NAMES, TAssetDetails, TNode, TNodeAssets } from '@paraspell/sdk'
Rename this fille to assetStore

2022-12-22 21:32 UTC, merged